// Main exports for the plugin
export { EventBus } from "./event-bus"
export { Journal } from "./journal"
export { Storage } from "./storage"
export { SystemEvent, SystemEventType } from "./events"
export { reflect } from "../reflection/engine"
export { buildTrajectory, Trajectory } from "../learning/trajectory"
export { detectPatterns, Pattern, PatternType } from "../learning/patterns"
export { createProposals, ImprovementProposal, ProposalCategory } from "../learning/proposals"
export { evaluatePromotion, PromotionDecision } from "../learning/promotion"
export { runEvaluation } from "../evaluation/runner"
export { EvaluationCase, EvaluationRun, EvaluationStatus } from "../evaluation/types"
export { TaskRequest } from "../routing/schemas"
export { createBaseline, Baseline } from "../evaluation/baseline"
export { compare, Comparison } from "../evaluation/comparator"
export { decide, Decision, DecisionAction } from "../evaluation/decision"
export { createExperiment, Experiment, ExperimentStatus } from "../isolation/experiment"
export { promote, reject } from "../isolation/lifecycle"
export { createWorktree } from "../isolation/workspace"
export { ModelRouter, RoutingDecision } from "../routing/router"
export { AgentRegistry } from "../routing/registry"
export { scoreAgent } from "../routing/scoring"
export { DEFAULT_PROFILES, AgentProfile } from "../routing/profiles"
export { Delegator, DelegationStep } from "../delegation/planner"
export { RoutingMemory, RoutingOutcome } from "../routing/memory"
export { SandboxExecutor, SandboxPolicy, DEFAULT_SANDBOX_POLICY } from "../execution/sandbox"
export { PluginConfig, DEFAULT_CONFIG } from "../config/schema"
export { learningCycle } from "../learning/cycle"